# Generated by Django 3.2.9 on 2021-11-03 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('publication_date', models.DateTimeField()),
                ('file', models.FileField(upload_to='files')),
                ('type', models.IntegerField(choices=[(1, 'Действуйщее законодательство'), (2, 'Проекты нормативных актов'), (3, 'Международные документы')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('publication_date', models.DateTimeField()),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('image', models.ImageField(upload_to='new')),
                ('link', models.URLField()),
                ('is_main', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('publication_date', models.DateTimeField()),
                ('file', models.FileField(upload_to='files')),
                ('type', models.IntegerField(choices=[(1, 'Публикации ICNL'), (2, 'Другие Публикации')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ImageNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.new')),
            ],
        ),
    ]
